# Generated by Django 4.1.7 on 2023-03-24 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='flightdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('time_taken', models.CharField(max_length=30)),
                ('ticket_rate', models.CharField(max_length=100)),
                ('no_of_stops', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=30)),
                ('from_code', models.CharField(max_length=30, null=True)),
                ('to_place', models.CharField(max_length=30)),
                ('to_code', models.CharField(max_length=30, null=True)),
                ('depart_time', models.CharField(max_length=30)),
                ('reach_time', models.CharField(max_length=30)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.flightdetails')),
            ],
        ),
    ]
