# Generated by Django 4.1.7 on 2023-03-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0005_alter_city_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='city'),
        ),
    ]
