# Generated by Django 4.1.7 on 2023-03-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0007_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
