# Generated by Django 4.1.7 on 2023-04-01 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0013_alter_testimonial_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='airportcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100)),
                ('airport_code', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_where', models.CharField(max_length=30)),
                ('where_to', models.CharField(max_length=30)),
                ('ticket_rate', models.CharField(max_length=100)),
                ('no_of_stops', models.CharField(max_length=30)),
                ('depart_date', models.DateField(null=True)),
                ('duration', models.CharField(max_length=30)),
                ('depart_time', models.CharField(max_length=30)),
                ('arrive_time', models.CharField(max_length=30)),
                ('no_stops', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='from_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='depart_time',
            new_name='flightname',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='from_place',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='plane',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='reach_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='to_code',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='to_place',
        ),
        migrations.AddField(
            model_name='flight',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='flight'),
        ),
        migrations.DeleteModel(
            name='flightdetails',
        ),
        migrations.AddField(
            model_name='trip',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.flight'),
        ),
        migrations.AddField(
            model_name='stops',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.trip'),
        ),
    ]
