# Generated by Django 4.1.7 on 2023-04-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0015_remove_trip_no_of_stops_remove_trip_ticket_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
    ]
