# Generated by Django 4.1.7 on 2023-04-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0017_alter_trip_arrive_time_alter_trip_depart_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
