# Generated by Django 4.1.7 on 2023-04-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0018_alter_trip_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='no_stops',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.IntegerField(),
        ),
    ]
